export const ActionTypes = {
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAILURE: "FETCH_FAILURE",
  ADD_POST: "ADD_POST",
  REMOVE_POST: "REMOVE_POST",
  ADD_TO_MYPOSTS: "ADD_TO_MYPOSTS",
  UPDATE_POST: "UPDATE_POST"
};
